project:
  type: website

website:
  title: "chekos' personal blog"
  description: "chekos' blog. data stuff and more."
  site-url: https://chekos.dev
  repo-url: https://github.com/chekos/chekos.dev
  reader-mode: true
  open-graph: true 
  twitter-card: 
    creator: "@ChekosWH"
    card-style: summary_large_image 
  navbar:
    logo: static/img/cimarron-logo-no-background.png
    background: secondary
    right:
      - about.qmd
      - icon: github
        aria-label: github
        href: https://github.com/chekos/chekos.dev
      - icon: twitter
        aria-label: twitter
        href: https://twitter.com/chekoswh
      - icon: mastodon
        aria-label: mastodon
        href: https://masto.tacosdedatos.com/@chekos
      - icon: person-circle
        aria-label: website
        href: https://soyserg.io
      - icon: instagram
        aria-label: instagram
        href: https://instagram.com/chekos.visuals
      - icon: rss
        aria-label: rss
        href: index.xml
        
format:
  html:
    theme:
      dark: darkly
      light: minty
    css: styles.css
    code-fold: true
    code-line-numbers: true
    code-copy: true
    toc: true
    toc-location: left
    anchor-sections: true
    title-block-categories: false
    title-block-banner: false

jupyter: python3
execute: 
  freeze: true
  error: false
  warning: false

author: "chekos"
