site_name: chekos' webblog
site_author: chekos
site_description: chekos' weblog
site_url: https://chekos.dev/

docs_dir: blog

theme:
  name: material
  custom_dir: overrides
  features:
    - header.autohide
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - content.code.copy
  logo: assets/cimarron-logo-no-background.png
  favicon: assets/icon.ico
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference

plugins:
  - search:
      lang:
        - en
        - es
  - blog:
      blog_dir: .
      blog_toc: true
      post_url_date_format: yyyy/MM
      archive_name: archive
      archive_date_format: MMMM yyyy
      categories_name: categories
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - tags:
      tags_file: tags.md
  - rss:
      match_path: posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  - social

nav:
  - home: index.md
  - about: about.md
  - tags: tags.md

hooks:
  - hooks/socialmedia.py
  - hooks/til-excerpt.py

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.socia/@chekoswh
      name: chekoswh on mastodon
    - icon: fontawesome/brands/github
      link: https://github.com/chekos
      name: chekos on github
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/chekos.visuals
      name: chekos.visuals on instagram
