name: Create Post from Issue

permissions:
  contents: write
  pull-requests: write

on:
  issues:
    types: [opened]

env:
  ISSUE_NUMBER: ${{ github.event.issue.number }}
  ISSUE_TITLE: ${{ github.event.issue.title }}
  ISSUE_BODY: ${{ github.event.issue.body }}
  ISSUE_LABELS: ${{ toJson(github.event.issue.labels) }}
  ISSUE_CREATED_AT: ${{ github.event.issue.created_at }}
  GH_TOKEN: ${{ github.token }}

jobs:
  create-post:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.user.login == github.repository_owner }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.5.1"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Generate Post from Issue
        run: >
          uv run --no-project scripts/issue-to-md.py 
          -t "$ISSUE_TITLE" 
          -b "$ISSUE_BODY" 
          -l "$ISSUE_LABELS" 
          -c "$ISSUE_CREATED_AT"

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b add-post-$ISSUE_NUMBER
          git add .
          git commit -m "Add post for Issue: $ISSUE_TITLE"
          git push -u origin add-post-$ISSUE_NUMBER
          gh pr create --title "#$ISSUE_NUMBER - $ISSUE_TITLE" --body "Adding new post. Closes #$ISSUE_NUMBER"
